config/routes.rb
Rails.application.routes.draw do
  resources :reports
  root "posts#index"
  get 'profiles/show'
  devise_for :users
  resources :posts
  resources :workreports
  resources :attendances, only: [:index]

  get "up" => "rails/health#show", as: :rails_health_check

  get '/profile', to: 'profiles#show', as: 'profile'


  get '/add_user', to: 'users#add_user', as: 'user'
  post '/add_user', to: 'users#add_user'

  resources :users, only: [:index, :new, :create ,:edit]
  # resources :add_users, path: 'add_user', only: [:index, :show, :new, :create, :edit, :update, :destroy]


  end

app/models/ability.rb
class Ability
  include CanCan::Ability

#   def initialize(current_user)

#     if(current_user.role_id==1)
#       can :manage, :all

#     elsif(current_user.role_id==6)
#         can :manage , :Workreport
#         can :manage , :Attendance
# end


def initialize(user)
  user ||= User.new

  if user.role_id == 1
    can :manage, :all
  elsif user.role_id == 2
      can :manage, :all

  elsif user.role_id == 3
        can :manage, :all

  elsif user.role_id == 4
          can :manage, :all

  elsif user.role_id == 5
            can :manage, :all
  elsif user.role_id == 6
    can :index, Workreport
    can :index, Attendance

  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :users
end

app/models/company.rb
class Company < ApplicationRecord
  # has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :users
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :reports
  # belongs_to :company

end

app/models/workreport.rb
class Workreport < ApplicationRecord
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    # Your existing update logic here

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
    @report = current_user.reports.build
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to reports_url, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy!

    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def report_params
    params.require(:report).permit(:report_date, :tasks, :hours, :minutes, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def add_user
    if params[:user].present?
      email = params[:user][:email]
      password = params[:user][:password]
      role_id = params[:user][:role_id]




      # Additional password constraints
      # if password_valid?(password)
        a = User.new(email: email, password: password, role_id: role_id)

        if a.save
          redirect_to users_path
        else
          render 'add_user'
        end
      # else
      #   flash[:alert] = 'Invalid password. Please follow the password constraints.'
      #   render 'add_user'
      # end
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role_id)
  end

  # def password_valid?(password)
  #   minimum_length = 8
  #   has_uppercase = /[A-Z]/.match?(password)
  #   has_lowercase = /[a-z]/.match?(password)
  #   has_digit = /\d/.match?(password)
  #   has_special_character = /[^A-Za-z\d]/.match?(password)

  #   password.length >= minimum_length &&
  #     has_uppercase &&
  #     has_lowercase &&
  #     has_digit &&
  #     has_special_character
  # end
end

app/helpers/addworkreport_helper.rb
module AddworkreportHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_duration(report)
    "#{report.hours}:#{"%02d" % report.minutes}"
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workreports_helper.rb
module WorkreportsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
    
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>
<br/>
<%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/index.html.erb
<style>
  .custom-button {
    background-color: #365486 !important;
    color: white !important;
    width: 20%;
    margin-bottom: 25px;
    text-align: center;
  }

  .custom-button:hover {
    background-color: #365486 !important;
    color: white !important;
    opacity: 0.8;
    
  }
   
</style>

   <div class="content">

    <div style="text-align: left; margin-top:100px">
  <h1>Reports</h1>
  
  
  
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Tasks</th>
        <th>Duration</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.report_date %></td>
          <td><%= report.tasks %></td>
          <td><%= display_duration(report) %></td>
          <td><%= report.status ? 'Completed' : 'In Progress' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
 <div style="position: absolute; top: 130px; right: 10px;">
      <%= link_to "Add Workreport", new_report_path, style: "color: white; text-decoration: none; padding: 10px; background-color: #365486; border-radius: 5px;" %>

    </div>
 <%= render 'layouts/sidebar' %>

app/views/reports/new.html.erb
<div class="sidebar">
  <div>
    <img src="https://i.imgur.com/9Q4oeZ3.png" alt="Logo" style="max-width: 80%; max-height: 80%;">

    <br/>

    <%= link_to "Dashbord", workreports_path, style: "color: white; text-decoration: none;" %>
    <br/>
    <br/>
    <%= link_to "Add Workreport", new_report_path, style: "color: white; text-decoration: none;" %>
    <br/>
    <br/>
    <%= link_to "Attendances", attendances_path, style: "color: white; text-decoration: none;" %>
    <br/>
    <br/>
    <%= link_to 'Profile', profile_path(current_user), style: "color: white; text-decoration: none;" %>
    <br/>
    <br/>
    <% if can? :create, User %>
      <%= link_to 'Manage User ', users_path, style: "color: white; text-decoration: none;" %>
      <br/>
    <% end %>
  </div>

  <div style="margin-top: auto; margin-bottom: 10px;">
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, style: "color: white; text-decoration: none;" %>
  </div>
</div>

<div class="content">
  <div style="text-align: left; margin-top: 100px;">
    <h1>Reports</h1>

    <%= form_for(@report) do |f| %>
      <div class="field">
        <%= f.label :report_date %><br />
        <%= f.date_field :report_date, class: "form-control", required: true %> <br />
      </div>

      <div class="field">
        <%= f.label :tasks %><br />
        <%= f.text_area :tasks, class: "form-control", required: true %> <br />
      </div>

      <div class="field">
        <div class="row">
          <div class="col">
            <%= f.label :Hour %><br />
            <%= f.select :hours, (0..23).to_a, { required: true }, class: "form-control" %>
          </div>

          <div class="col">
            <%= f.label :Minute %><br />
            <%= f.select :minutes, (0..59).to_a, { required: true }, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="field">
        <%= f.label :status %><br />
        <%= f.select :status, options_for_select(['inprogress', 'complete']), { required: true }, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Submit", class: "btn btn-primary", style: "background-color: #365486; border-color: #365486;" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @report %>

<div>
  <%= link_to "Edit this report", edit_report_path(@report) %> |
  <%= link_to "Back to reports", reports_path %>

  <%= button_to "Destroy this report", @report, method: :delete %>
</div>

app/views/users/add_user.html.erb
  <div class="content">

    <div style="text-align: left; margin-top:100px">
    <h1>Add User</h1>

    <%= form_for(:user, url: user_path, data: { turbo: false }) do |f| %>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em><%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :role_id %><br />
        <%= f.collection_select :role_id, Role.all, :id, :role_name, { prompt: "Select a role" }, class: "form-select" %>
      </div>
      <br/>
      <div class="actions">
        <%= f.submit "Add", class: "btn btn-primary", style: "width:100px;  background-color: #365486; border-color: #365486;" %>
      </div>

    <% end %>


  </div>
</div>
   <%= render 'layouts/sidebar' %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
 

  <br/>

  <%= f.submit 'Update Profile' %>
<% end %>
 <%= render 'layouts/sidebar' %>

app/views/users/index.html.erb
<style>
    .custom-button {
      background-color: #365486 !important;
      color: white !important;
      width: 100%;
      margin-bottom: 15px;
    }

    .custom-button:hover {
      background-color: #365486 !important;
      color: white !important;
      opacity: 0.8;
    }
  </style>



   <div class="content">

    <div style="text-align: left; margin-top:100px">
      <h1>All Users</h1>

      <% if @users.any? %>
        <table class="table table-bordered table-striped">
       
          <thead class="thead-dark">
            <tr>
              <th>Email</th>
              <th>Role</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.role.role_name %></td>
                <td>
                  <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-warning btn-sm custom-button", style: "margin-right: 5px;" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No users found.</p>
      <% end %>
    </div>
  </div>
   <div style="position: absolute; top: 130px; right: 10px;">
      <%= link_to 'Add user', user_path, style: "color: white; text-decoration: none; padding: 10px; background-color: #365486; border-radius: 5px;" %>

    </div>

 <%= render 'layouts/sidebar' %>